# Generated by Django 4.2.3 on 2023-08-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models_generation', to='cars.modelsgeneration')),
            ],
        ),
    ]
