# Generated by Django 4.2.3 on 2023-08-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('year_of_manufacture', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic'), ('robotic', 'robotic')], max_length=20)),
                ('steering_wheel_position', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=20)),
                ('Color', models.CharField(max_length=30)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars_models', to='cars.carsmodel')),
            ],
        ),
    ]
