# Generated by Django 4.2.3 on 2023-08-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle', smart_selects.db_fields.ChainedForeignKey(chained_field='vehicle', chained_model_field='vehicle', on_delete=django.db.models.deletion.CASCADE, to='adverts.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_of_manufacture', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2)),
                ('engine_type', models.CharField(choices=[('gasoline', 'gasoline'), ('diesel', 'diesel'), ('electric', 'electric')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic'), ('variator', 'variator')], max_length=20)),
                ('condition', models.CharField(blank=True, max_length=30)),
                ('status', models.IntegerField(choices=[(0, 'Deactivated'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adverts.category')),
                ('mod', smart_selects.db_fields.ChainedForeignKey(chained_field='vehicle', chained_model_field='vehicle', on_delete=django.db.models.deletion.CASCADE, to='adverts.vehicle')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advert_models', to='adverts.vehiclemodel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advert_vehicles', to='adverts.vehicle')),
            ],
        ),
    ]
