# Generated by Django 4.2.3 on 2023-08-27 16:17

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='mod',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='mod', chained_model_field='vehiclemodel', on_delete=django.db.models.deletion.CASCADE, to='adverts.vehiclemodel'),
        ),
    ]
