# Generated by Django 4.2.3 on 2023-08-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_remove_advert_mod_remove_advert_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='adverts.vehicle'),
        ),
    ]
