# Generated by Django 4.2.3 on 2023-08-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_vehiclemodel_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='advert_models', to='adverts.vehiclemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='advert_vehicles', to='adverts.vehicle'),
            preserve_default=False,
        ),
    ]
