# Generated by Django 4.2.3 on 2023-08-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_advert_model_advert_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='year_of_manufacture',
        ),
        migrations.CreateModel(
            name='ModelYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='adverts.vehiclemodel')),
            ],
        ),
        migrations.AddField(
            model_name='advert',
            name='model_year',
            field=models.ForeignKey(default=1900, on_delete=django.db.models.deletion.PROTECT, related_name='advert_year', to='adverts.modelyear'),
            preserve_default=False,
        ),
    ]
