# Generated by Django 4.2.3 on 2023-08-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_advert_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='generation',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
    ]
