# Generated by Django 4.2.3 on 2023-08-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_remove_advert_generation_delete_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
